// -*- C++ -*-
#ifndef ZMET2016_H
#define ZMET2016_H
#include "Math/LorentzVector.h"
#include "Math/Point3D.h"
#include "TMath.h"
#include "TBranch.h"
#include "TTree.h"
#include "TH1F.h"
#include "TFile.h"
#include "TBits.h"
#include <vector>
#include <unistd.h>
typedef ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > LorentzVector;

// Generated with file: /hadoop/cms/store/user/bsathian/ZMET_babies_20200203/TTZToLLNuNu_M-10_TuneCUETP8M1_13TeV-amcatnlo-pythia8_RunIISummer16MiniAODv3-PUMoriond17_94X_mcRun2_asymptotic_v3_ext2-v1_MINIAODSIM_ZMET_babies/baby_1.root

using namespace std;
class ZMET2016 {
private:
protected:
  unsigned int index;
  int HLT_Mu37_Ele27_CaloIdL_MW_;
  TBranch *HLT_Mu37_Ele27_CaloIdL_MW_branch;
  bool HLT_Mu37_Ele27_CaloIdL_MW_isLoaded;
  vector<float> *ak8jets_tau1_;
  TBranch *ak8jets_tau1_branch;
  bool ak8jets_tau1_isLoaded;
  vector<float> *ak8jets_tau3_;
  TBranch *ak8jets_tau3_branch;
  bool ak8jets_tau3_isLoaded;
  vector<float> *ak8jets_tau2_;
  TBranch *ak8jets_tau2_branch;
  bool ak8jets_tau2_isLoaded;
  int HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZ_;
  TBranch *HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZ_branch;
  bool HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZ_isLoaded;
  int HLT_Mu27_TkMu8_;
  TBranch *HLT_Mu27_TkMu8_branch;
  bool HLT_Mu27_TkMu8_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *genPart_p4_;
  TBranch *genPart_p4_branch;
  bool genPart_p4_isLoaded;
  int HLT_Mu50_;
  TBranch *HLT_Mu50_branch;
  bool HLT_Mu50_isLoaded;
  int HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_;
  TBranch *HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_branch;
  bool HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_isLoaded;
  int HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_isLoaded;
  int nisoTrack_5gev_;
  TBranch *nisoTrack_5gev_branch;
  bool nisoTrack_5gev_isLoaded;
  float nupfcands_2430_phi_;
  TBranch *nupfcands_2430_phi_branch;
  bool nupfcands_2430_phi_isLoaded;
  int Flag_badMuonFilterv2_;
  TBranch *Flag_badMuonFilterv2_branch;
  bool Flag_badMuonFilterv2_isLoaded;
  vector<float> *isotrack_absiso_;
  TBranch *isotrack_absiso_branch;
  bool isotrack_absiso_isLoaded;
  float phpfcands_2430_phi_;
  TBranch *phpfcands_2430_phi_branch;
  bool phpfcands_2430_phi_isLoaded;
  int HLT_IsoMu27_;
  TBranch *HLT_IsoMu27_branch;
  bool HLT_IsoMu27_isLoaded;
  vector<float> *genPart_pt_;
  TBranch *genPart_pt_branch;
  bool genPart_pt_isLoaded;
  float isr_unc_;
  TBranch *isr_unc_branch;
  bool isr_unc_isLoaded;
  float sum_mlb_;
  TBranch *sum_mlb_branch;
  bool sum_mlb_isLoaded;
  float met_miniaod_pt_;
  TBranch *met_miniaod_pt_branch;
  bool met_miniaod_pt_isLoaded;
  vector<int> *lep_charge_;
  TBranch *lep_charge_branch;
  bool lep_charge_isLoaded;
  int nlep_;
  TBranch *nlep_branch;
  bool nlep_isLoaded;
  float met_genPhi_;
  TBranch *met_genPhi_branch;
  bool met_genPhi_isLoaded;
  float phpfcands_0013_sumet_;
  TBranch *phpfcands_0013_sumet_branch;
  bool phpfcands_0013_sumet_isLoaded;
  vector<int> *lep_lostHits_;
  TBranch *lep_lostHits_branch;
  bool lep_lostHits_isLoaded;
  unsigned long long evt_;
  TBranch *evt_branch;
  bool evt_isLoaded;
  vector<int> *gamma_idCutBased_;
  TBranch *gamma_idCutBased_branch;
  bool gamma_idCutBased_isLoaded;
  vector<int> *genLepFromTau_status_;
  TBranch *genLepFromTau_status_branch;
  bool genLepFromTau_status_isLoaded;
  float dphi_genmetj1_;
  TBranch *dphi_genmetj1_branch;
  bool dphi_genmetj1_isLoaded;
  int njets_;
  TBranch *njets_branch;
  bool njets_isLoaded;
  int mass_LSP_;
  TBranch *mass_LSP_branch;
  bool mass_LSP_isLoaded;
  vector<float> *weightsf_lepip_FS_;
  TBranch *weightsf_lepip_FS_branch;
  bool weightsf_lepip_FS_isLoaded;
  vector<float> *genTau_phi_;
  TBranch *genTau_phi_branch;
  bool genTau_phi_isLoaded;
  vector<int> *ak8jets_parton_flavor_;
  TBranch *ak8jets_parton_flavor_branch;
  bool ak8jets_parton_flavor_isLoaded;
  int HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_isLoaded;
  float nupfcands_1316_sumet_;
  TBranch *nupfcands_1316_sumet_branch;
  bool nupfcands_1316_sumet_isLoaded;
  vector<float> *jets_csv_;
  TBranch *jets_csv_branch;
  bool jets_csv_isLoaded;
  float dphi_metj2_dn_;
  TBranch *dphi_metj2_dn_branch;
  bool dphi_metj2_dn_isLoaded;
  int Flag_eeBadScFilter_;
  TBranch *Flag_eeBadScFilter_branch;
  bool Flag_eeBadScFilter_isLoaded;
  vector<float> *jets_up_csv_;
  TBranch *jets_up_csv_branch;
  bool jets_up_csv_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *decayedphoton_bosn_p4_;
  TBranch *decayedphoton_bosn_p4_branch;
  bool decayedphoton_bosn_p4_isLoaded;
  float dR_jj_dn_;
  TBranch *dR_jj_dn_branch;
  bool dR_jj_dn_isLoaded;
  vector<int> *genLep_motherIndex_;
  TBranch *genLep_motherIndex_branch;
  bool genLep_motherIndex_isLoaded;
  vector<float> *gamma_phIso_;
  TBranch *gamma_phIso_branch;
  bool gamma_phIso_isLoaded;
  vector<float> *lep_etaSC_;
  TBranch *lep_etaSC_branch;
  bool lep_etaSC_isLoaded;
  vector<float> *lep_MVA_;
  TBranch *lep_MVA_branch;
  bool lep_MVA_isLoaded;
  int nBJetTight25_;
  TBranch *nBJetTight25_branch;
  bool nBJetTight25_isLoaded;
  int nBJetMedium35_dn_;
  TBranch *nBJetMedium35_dn_branch;
  bool nBJetMedium35_dn_isLoaded;
  int nTaus20_;
  TBranch *nTaus20_branch;
  bool nTaus20_isLoaded;
  float met_T1CHS_miniAOD_CORE_dn_phi_;
  TBranch *met_T1CHS_miniAOD_CORE_dn_phi_branch;
  bool met_T1CHS_miniAOD_CORE_dn_phi_isLoaded;
  float phpfcands_30in_sumet_;
  TBranch *phpfcands_30in_sumet_branch;
  bool phpfcands_30in_sumet_isLoaded;
  vector<float> *lep_phi_;
  TBranch *lep_phi_branch;
  bool lep_phi_isLoaded;
  float met_T1CHS_fromCORE_pt_;
  TBranch *met_T1CHS_fromCORE_pt_branch;
  bool met_T1CHS_fromCORE_pt_isLoaded;
  float sum_mlb_dn_;
  TBranch *sum_mlb_dn_branch;
  bool sum_mlb_dn_isLoaded;
  vector<float> *genPart_mass_;
  TBranch *genPart_mass_branch;
  bool genPart_mass_isLoaded;
  bool HLT_Photon120_R9Id90_HE10_IsoM_matchedtophoton_;
  TBranch *HLT_Photon120_R9Id90_HE10_IsoM_matchedtophoton_branch;
  bool HLT_Photon120_R9Id90_HE10_IsoM_matchedtophoton_isLoaded;
  vector<float> *genLepFromTau_charge_;
  TBranch *genLepFromTau_charge_branch;
  bool genLepFromTau_charge_isLoaded;
  int evt_nEvts_;
  TBranch *evt_nEvts_branch;
  bool evt_nEvts_isLoaded;
  bool HLT_Photon165_HE10_matchedtophoton_;
  TBranch *HLT_Photon165_HE10_matchedtophoton_branch;
  bool HLT_Photon165_HE10_matchedtophoton_isLoaded;
  float met_calo_pt_;
  TBranch *met_calo_pt_branch;
  bool met_calo_pt_isLoaded;
  float gen_ht_;
  TBranch *gen_ht_branch;
  bool gen_ht_isLoaded;
  int HLT_Mu30_TkMu11_;
  TBranch *HLT_Mu30_TkMu11_branch;
  bool HLT_Mu30_TkMu11_isLoaded;
  float deta_jj_dn_;
  TBranch *deta_jj_dn_branch;
  bool deta_jj_dn_isLoaded;
  int nBJetLoose25_;
  TBranch *nBJetLoose25_branch;
  bool nBJetLoose25_isLoaded;
  bool HLT_Photon50_R9Id90_HE10_IsoM_matchedtophoton_;
  TBranch *HLT_Photon50_R9Id90_HE10_IsoM_matchedtophoton_branch;
  bool HLT_Photon50_R9Id90_HE10_IsoM_matchedtophoton_isLoaded;
  vector<float> *gamma_mass_;
  TBranch *gamma_mass_branch;
  bool gamma_mass_isLoaded;
  float evt_scale1fb_;
  TBranch *evt_scale1fb_branch;
  bool evt_scale1fb_isLoaded;
  float met_calo_phi_;
  TBranch *met_calo_phi_branch;
  bool met_calo_phi_isLoaded;
  int HLT_Mu27_Ele37_CaloIdL_MW_;
  TBranch *HLT_Mu27_Ele37_CaloIdL_MW_branch;
  bool HLT_Mu27_Ele37_CaloIdL_MW_isLoaded;
  float phpfcands_2430_pt_;
  TBranch *phpfcands_2430_pt_branch;
  bool phpfcands_2430_pt_isLoaded;
  float mjj_mindphi_;
  TBranch *mjj_mindphi_branch;
  bool mjj_mindphi_isLoaded;
  vector<float> *genTau_mass_;
  TBranch *genTau_mass_branch;
  bool genTau_mass_isLoaded;
  int nJet200MuFrac50DphiMet_;
  TBranch *nJet200MuFrac50DphiMet_branch;
  bool nJet200MuFrac50DphiMet_isLoaded;
  vector<float> *genLepFromTau_phi_;
  TBranch *genLepFromTau_phi_branch;
  bool genLepFromTau_phi_isLoaded;
  float chpfcands_2430_sumet_;
  TBranch *chpfcands_2430_sumet_branch;
  bool chpfcands_2430_sumet_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *decayedphoton_lep1_p4_;
  TBranch *decayedphoton_lep1_p4_branch;
  bool decayedphoton_lep1_p4_isLoaded;
  vector<float> *genLep_pt_;
  TBranch *genLep_pt_branch;
  bool genLep_pt_isLoaded;
  vector<float> *gamma_hOverE_online_;
  TBranch *gamma_hOverE_online_branch;
  bool gamma_hOverE_online_isLoaded;
  int HLT_singleMu_noiso_;
  TBranch *HLT_singleMu_noiso_branch;
  bool HLT_singleMu_noiso_isLoaded;
  float mbb_bpt_dn_;
  TBranch *mbb_bpt_dn_branch;
  bool mbb_bpt_dn_isLoaded;
  bool HLT_Photon165_R9Id90_HE10_IsoM_matchedtophoton_;
  TBranch *HLT_Photon165_R9Id90_HE10_IsoM_matchedtophoton_branch;
  bool HLT_Photon165_R9Id90_HE10_IsoM_matchedtophoton_isLoaded;
  float met_T1CHS_miniAOD_CORE_phi_;
  TBranch *met_T1CHS_miniAOD_CORE_phi_branch;
  bool met_T1CHS_miniAOD_CORE_phi_isLoaded;
  float nupfcands_2430_sumet_;
  TBranch *nupfcands_2430_sumet_branch;
  bool nupfcands_2430_sumet_isLoaded;
  int HLT_singleMu_;
  TBranch *HLT_singleMu_branch;
  bool HLT_singleMu_isLoaded;
  float mt2_genmet_;
  TBranch *mt2_genmet_branch;
  bool mt2_genmet_isLoaded;
  float phpfcands_30in_phi_;
  TBranch *phpfcands_30in_phi_branch;
  bool phpfcands_30in_phi_isLoaded;
  float nupfcands_1624_sumet_;
  TBranch *nupfcands_1624_sumet_branch;
  bool nupfcands_1624_sumet_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_dn_p4_;
  TBranch *jets_dn_p4_branch;
  bool jets_dn_p4_isLoaded;
  float phpfcands_1316_phi_;
  TBranch *phpfcands_1316_phi_branch;
  bool phpfcands_1316_phi_isLoaded;
  int nisoTrack_mt2_;
  TBranch *nisoTrack_mt2_branch;
  bool nisoTrack_mt2_isLoaded;
  float chpfcands_30in_pt_;
  TBranch *chpfcands_30in_pt_branch;
  bool chpfcands_30in_pt_isLoaded;
  int nisoTrack_PFEle5_woverlaps_;
  TBranch *nisoTrack_PFEle5_woverlaps_branch;
  bool nisoTrack_PFEle5_woverlaps_isLoaded;
  float nupfcands_30in_phi_;
  TBranch *nupfcands_30in_phi_branch;
  bool nupfcands_30in_phi_isLoaded;
  vector<int> *lep_tightCharge_;
  TBranch *lep_tightCharge_branch;
  bool lep_tightCharge_isLoaded;
  int nBJetLoose35_;
  TBranch *nBJetLoose35_branch;
  bool nBJetLoose35_isLoaded;
  int Flag_HBHEIsoNoiseFilter_;
  TBranch *Flag_HBHEIsoNoiseFilter_branch;
  bool Flag_HBHEIsoNoiseFilter_isLoaded;
  int HLT_Photon30_R9Id90_HE10_IsoM_;
  TBranch *HLT_Photon30_R9Id90_HE10_IsoM_branch;
  bool HLT_Photon30_R9Id90_HE10_IsoM_isLoaded;
  vector<float> *lep_glb_x2ondof_;
  TBranch *lep_glb_x2ondof_branch;
  bool lep_glb_x2ondof_isLoaded;
  vector<int> *genLepFromTau_sourceId_;
  TBranch *genLepFromTau_sourceId_branch;
  bool genLepFromTau_sourceId_isLoaded;
  float met_rawPt_;
  TBranch *met_rawPt_branch;
  bool met_rawPt_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *decayedphoton_lep2_p4_;
  TBranch *decayedphoton_lep2_p4_branch;
  bool decayedphoton_lep2_p4_isLoaded;
  float met_muegclean_pt_;
  TBranch *met_muegclean_pt_branch;
  bool met_muegclean_pt_isLoaded;
  int HLT_Mu30_Ele30_CaloIdL_GsfTrkIdVL_;
  TBranch *HLT_Mu30_Ele30_CaloIdL_GsfTrkIdVL_branch;
  bool HLT_Mu30_Ele30_CaloIdL_GsfTrkIdVL_isLoaded;
  float met_T1CHS_pt_;
  TBranch *met_T1CHS_pt_branch;
  bool met_T1CHS_pt_isLoaded;
  float dphi_metj1_up_;
  TBranch *dphi_metj1_up_branch;
  bool dphi_metj1_up_isLoaded;
  int lumi_;
  TBranch *lumi_branch;
  bool lumi_isLoaded;
  bool elveto_;
  TBranch *elveto_branch;
  bool elveto_isLoaded;
  int HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_;
  TBranch *HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_branch;
  bool HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_isLoaded;
  float chpfcands_30in_phi_;
  TBranch *chpfcands_30in_phi_branch;
  bool chpfcands_30in_phi_isLoaded;
  float mjj_;
  TBranch *mjj_branch;
  bool mjj_isLoaded;
  float chpfcands_0013_pt_;
  TBranch *chpfcands_0013_pt_branch;
  bool chpfcands_0013_pt_isLoaded;
  vector<int> *lep_pdgId_;
  TBranch *lep_pdgId_branch;
  bool lep_pdgId_isLoaded;
  bool HLT_Photon30_R9Id90_HE10_IsoM_matchedtophoton_;
  TBranch *HLT_Photon30_R9Id90_HE10_IsoM_matchedtophoton_branch;
  bool HLT_Photon30_R9Id90_HE10_IsoM_matchedtophoton_isLoaded;
  vector<float> *lep_relIso03_;
  TBranch *lep_relIso03_branch;
  bool lep_relIso03_isLoaded;
  vector<float> *lep_relIso04_;
  TBranch *lep_relIso04_branch;
  bool lep_relIso04_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *gamma_p4_;
  TBranch *gamma_p4_branch;
  bool gamma_p4_isLoaded;
  int Flag_EcalDeadCellTriggerPrimitiveFilter_;
  TBranch *Flag_EcalDeadCellTriggerPrimitiveFilter_branch;
  bool Flag_EcalDeadCellTriggerPrimitiveFilter_isLoaded;
  bool HLT_Photon22_R9Id90_HE10_IsoM_matchedtophoton_;
  TBranch *HLT_Photon22_R9Id90_HE10_IsoM_matchedtophoton_branch;
  bool HLT_Photon22_R9Id90_HE10_IsoM_matchedtophoton_isLoaded;
  int nBJetMedium25_;
  TBranch *nBJetMedium25_branch;
  bool nBJetMedium25_isLoaded;
  int nBJetLoose25_dn_;
  TBranch *nBJetLoose25_dn_branch;
  bool nBJetLoose25_dn_isLoaded;
  vector<float> *lep_pt_;
  TBranch *lep_pt_branch;
  bool lep_pt_isLoaded;
  float weight_L1prefire_down_;
  TBranch *weight_L1prefire_down_branch;
  bool weight_L1prefire_down_isLoaded;
  int nBJetTight25_dn_;
  TBranch *nBJetTight25_dn_branch;
  bool nBJetTight25_dn_isLoaded;
  vector<float> *gamma_pt_;
  TBranch *gamma_pt_branch;
  bool gamma_pt_isLoaded;
  vector<float> *highPtPFcands_dz_;
  TBranch *highPtPFcands_dz_branch;
  bool highPtPFcands_dz_isLoaded;
  vector<float> *weightsf_lepid_FS_;
  TBranch *weightsf_lepid_FS_branch;
  bool weightsf_lepid_FS_isLoaded;
  vector<int> *genTau_sourceId_;
  TBranch *genTau_sourceId_branch;
  bool genTau_sourceId_isLoaded;
  float chpfcands_0013_phi_;
  TBranch *chpfcands_0013_phi_branch;
  bool chpfcands_0013_phi_isLoaded;
  int Flag_hcalLaserEventFilter_;
  TBranch *Flag_hcalLaserEventFilter_branch;
  bool Flag_hcalLaserEventFilter_isLoaded;
  int HLT_Photon165_R9Id90_HE10_IsoM_;
  TBranch *HLT_Photon165_R9Id90_HE10_IsoM_branch;
  bool HLT_Photon165_R9Id90_HE10_IsoM_isLoaded;
  float chpfcands_2430_pt_;
  TBranch *chpfcands_2430_pt_branch;
  bool chpfcands_2430_pt_isLoaded;
  float dphi_jj_;
  TBranch *dphi_jj_branch;
  bool dphi_jj_isLoaded;
  int nBJetLoose35_up_;
  TBranch *nBJetLoose35_up_branch;
  bool nBJetLoose35_up_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_medb_p4_;
  TBranch *jets_medb_p4_branch;
  bool jets_medb_p4_isLoaded;
  vector<int> *gamma_mcMatchId_;
  TBranch *gamma_mcMatchId_branch;
  bool gamma_mcMatchId_isLoaded;
  float nupfcands_1316_phi_;
  TBranch *nupfcands_1316_phi_branch;
  bool nupfcands_1316_phi_isLoaded;
  float met_muegclean_phi_;
  TBranch *met_muegclean_phi_branch;
  bool met_muegclean_phi_isLoaded;
  vector<bool> *genPart_isp6status3_;
  TBranch *genPart_isp6status3_branch;
  bool genPart_isp6status3_isLoaded;
  vector<float> *lep_x2ondof_;
  TBranch *lep_x2ondof_branch;
  bool lep_x2ondof_isLoaded;
  float ht_dn_;
  TBranch *ht_dn_branch;
  bool ht_dn_isLoaded;
  int ngenLep_;
  TBranch *ngenLep_branch;
  bool ngenLep_isLoaded;
  int year_;
  TBranch *year_branch;
  bool year_isLoaded;
  int HLT_DoubleEle27_CaloIdL_MW_Edge_;
  TBranch *HLT_DoubleEle27_CaloIdL_MW_Edge_branch;
  bool HLT_DoubleEle27_CaloIdL_MW_Edge_isLoaded;
  vector<float> *genLepFromTau_eta_;
  TBranch *genLepFromTau_eta_branch;
  bool genLepFromTau_eta_isLoaded;
  int HLT_ECALHT800_NoJetID_;
  TBranch *HLT_ECALHT800_NoJetID_branch;
  bool HLT_ECALHT800_NoJetID_isLoaded;
  vector<float> *gamma_genPt_;
  TBranch *gamma_genPt_branch;
  bool gamma_genPt_isLoaded;
  float mt2_up_;
  TBranch *mt2_up_branch;
  bool mt2_up_isLoaded;
  float mjj_up_;
  TBranch *mjj_up_branch;
  bool mjj_up_isLoaded;
  vector<unsigned long> *isotrack_index_;
  TBranch *isotrack_index_branch;
  bool isotrack_index_isLoaded;
  float nupfcands_0013_sumet_;
  TBranch *nupfcands_0013_sumet_branch;
  bool nupfcands_0013_sumet_isLoaded;
  float dphi_metj2_up_;
  TBranch *dphi_metj2_up_branch;
  bool dphi_metj2_up_isLoaded;
  float dphi_metj3_up_;
  TBranch *dphi_metj3_up_branch;
  bool dphi_metj3_up_isLoaded;
  vector<int> *isotrack_pdgId_;
  TBranch *isotrack_pdgId_branch;
  bool isotrack_pdgId_isLoaded;
  float evt_kfactor_;
  TBranch *evt_kfactor_branch;
  bool evt_kfactor_isLoaded;
  int nBJetMedium35_up_;
  TBranch *nBJetMedium35_up_branch;
  bool nBJetMedium35_up_isLoaded;
  int HLT_CaloJet500_NoJetID_;
  TBranch *HLT_CaloJet500_NoJetID_branch;
  bool HLT_CaloJet500_NoJetID_isLoaded;
  vector<float> *lep_relIso03MRDB_;
  TBranch *lep_relIso03MRDB_branch;
  bool lep_relIso03MRDB_isLoaded;
  int ngenLepFromTau_;
  TBranch *ngenLepFromTau_branch;
  bool ngenLepFromTau_isLoaded;
  float dphi_genmetj3_;
  TBranch *dphi_genmetj3_branch;
  bool dphi_genmetj3_isLoaded;
  float dphi_metj3_dn_;
  TBranch *dphi_metj3_dn_branch;
  bool dphi_metj3_dn_isLoaded;
  int HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_isLoaded;
  int HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass8_;
  TBranch *HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass8_branch;
  bool HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass8_isLoaded;
  int HLT_singleEl_;
  TBranch *HLT_singleEl_branch;
  bool HLT_singleEl_isLoaded;
  int HLT_Photon75_R9Id90_HE10_IsoM_;
  TBranch *HLT_Photon75_R9Id90_HE10_IsoM_branch;
  bool HLT_Photon75_R9Id90_HE10_IsoM_isLoaded;
  float dRll_;
  TBranch *dRll_branch;
  bool dRll_isLoaded;
  int njets_dn_;
  TBranch *njets_dn_branch;
  bool njets_dn_isLoaded;
  int isr_njets_;
  TBranch *isr_njets_branch;
  bool isr_njets_isLoaded;
  vector<float> *gamma_ecpfclusiso_;
  TBranch *gamma_ecpfclusiso_branch;
  bool gamma_ecpfclusiso_isLoaded;
  float weight_L1prefire_up_;
  TBranch *weight_L1prefire_up_branch;
  bool weight_L1prefire_up_isLoaded;
  float phpfcands_30in_pt_;
  TBranch *phpfcands_30in_pt_branch;
  bool phpfcands_30in_pt_isLoaded;
  int HLT_Photon165_HE10_;
  TBranch *HLT_Photon165_HE10_branch;
  bool HLT_Photon165_HE10_isLoaded;
  float nupfcands_0013_pt_;
  TBranch *nupfcands_0013_pt_branch;
  bool nupfcands_0013_pt_isLoaded;
  vector<float> *genLep_eta_;
  TBranch *genLep_eta_branch;
  bool genLep_eta_isLoaded;
  int nJetFailId_;
  TBranch *nJetFailId_branch;
  bool nJetFailId_isLoaded;
  int Flag_HBHENoiseFilter_;
  TBranch *Flag_HBHENoiseFilter_branch;
  bool Flag_HBHENoiseFilter_isLoaded;
  float deta_jj_;
  TBranch *deta_jj_branch;
  bool deta_jj_isLoaded;
  float metsig_unofficial_dn_;
  TBranch *metsig_unofficial_dn_branch;
  bool metsig_unofficial_dn_isLoaded;
  float dR_jj_;
  TBranch *dR_jj_branch;
  bool dR_jj_isLoaded;
  int nFatJets_;
  TBranch *nFatJets_branch;
  bool nFatJets_isLoaded;
  int HLT_Mu37_TkMu27_;
  TBranch *HLT_Mu37_TkMu27_branch;
  bool HLT_Mu37_TkMu27_isLoaded;
  float nupfcands_30in_sumet_;
  TBranch *nupfcands_30in_sumet_branch;
  bool nupfcands_30in_sumet_isLoaded;
  float mjj_mindphi_up_;
  TBranch *mjj_mindphi_up_branch;
  bool mjj_mindphi_up_isLoaded;
  int nBJetLoose35_dn_;
  TBranch *nBJetLoose35_dn_branch;
  bool nBJetLoose35_dn_isLoaded;
  float mbb_bpt_up_;
  TBranch *mbb_bpt_up_branch;
  bool mbb_bpt_up_isLoaded;
  vector<float> *genTau_pt_;
  TBranch *genTau_pt_branch;
  bool genTau_pt_isLoaded;
  int Flag_noBadMuons_;
  TBranch *Flag_noBadMuons_branch;
  bool Flag_noBadMuons_isLoaded;
  vector<float> *lep_dz_;
  TBranch *lep_dz_branch;
  bool lep_dz_isLoaded;
  vector<float> *gamma_eta_;
  TBranch *gamma_eta_branch;
  bool gamma_eta_isLoaded;
  vector<float> *genPart_phi_;
  TBranch *genPart_phi_branch;
  bool genPart_phi_isLoaded;
  vector<float> *weightsf_lepiso_;
  TBranch *weightsf_lepiso_branch;
  bool weightsf_lepiso_isLoaded;
  int Flag_CSCTightHaloFilter_;
  TBranch *Flag_CSCTightHaloFilter_branch;
  bool Flag_CSCTightHaloFilter_isLoaded;
  int nBJetLoose25_up_;
  TBranch *nBJetLoose25_up_branch;
  bool nBJetLoose25_up_isLoaded;
  int HLT_Mu33_Ele33_CaloIdL_GsfTrkIdVL_;
  TBranch *HLT_Mu33_Ele33_CaloIdL_GsfTrkIdVL_branch;
  bool HLT_Mu33_Ele33_CaloIdL_GsfTrkIdVL_isLoaded;
  vector<int> *lep_tightId_;
  TBranch *lep_tightId_branch;
  bool lep_tightId_isLoaded;
  int nBJetMedium25_up_;
  TBranch *nBJetMedium25_up_branch;
  bool nBJetMedium25_up_isLoaded;
  float met_T1CHS_miniAOD_CORE_up_phi_;
  TBranch *met_T1CHS_miniAOD_CORE_up_phi_branch;
  bool met_T1CHS_miniAOD_CORE_up_phi_isLoaded;
  float phpfcands_1624_sumet_;
  TBranch *phpfcands_1624_sumet_branch;
  bool phpfcands_1624_sumet_isLoaded;
  int HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_isLoaded;
  float met_phi_;
  TBranch *met_phi_branch;
  bool met_phi_isLoaded;
  vector<int> *genTau_status_;
  TBranch *genTau_status_branch;
  bool genTau_status_isLoaded;
  vector<float> *genLep_mass_;
  TBranch *genLep_mass_branch;
  bool genLep_mass_isLoaded;
  float met_T1CHS_phi_;
  TBranch *met_T1CHS_phi_branch;
  bool met_T1CHS_phi_isLoaded;
  float rho_;
  TBranch *rho_branch;
  bool rho_isLoaded;
  float dphi_metj1_dn_;
  TBranch *dphi_metj1_dn_branch;
  bool dphi_metj1_dn_isLoaded;
  int HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_;
  TBranch *HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_branch;
  bool HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_isLoaded;
  int mass_gluino_;
  TBranch *mass_gluino_branch;
  bool mass_gluino_isLoaded;
  int HLT_DoubleEle33_CaloIdL_MW_;
  TBranch *HLT_DoubleEle33_CaloIdL_MW_branch;
  bool HLT_DoubleEle33_CaloIdL_MW_isLoaded;
  vector<TString> *evt_dataset_;
  TBranch *evt_dataset_branch;
  bool evt_dataset_isLoaded;
  vector<float> *lep_pterr_;
  TBranch *lep_pterr_branch;
  bool lep_pterr_isLoaded;
  float weight_btagsf_heavy_DN_;
  TBranch *weight_btagsf_heavy_DN_branch;
  bool weight_btagsf_heavy_DN_isLoaded;
  int Flag_badChargedCandidateFilter_;
  TBranch *Flag_badChargedCandidateFilter_branch;
  bool Flag_badChargedCandidateFilter_isLoaded;
  int Flag_badChargedCandidateFilterv2_;
  TBranch *Flag_badChargedCandidateFilterv2_branch;
  bool Flag_badChargedCandidateFilterv2_isLoaded;
  vector<float> *lep_sta_x2ondof_;
  TBranch *lep_sta_x2ondof_branch;
  bool lep_sta_x2ondof_isLoaded;
  float dphi_genmetj2_;
  TBranch *dphi_genmetj2_branch;
  bool dphi_genmetj2_isLoaded;
  int nMuons10_;
  TBranch *nMuons10_branch;
  bool nMuons10_isLoaded;
  int evt_type_;
  TBranch *evt_type_branch;
  bool evt_type_isLoaded;
  int HLT_Photon36_R9Id90_HE10_IsoM_;
  TBranch *HLT_Photon36_R9Id90_HE10_IsoM_branch;
  bool HLT_Photon36_R9Id90_HE10_IsoM_isLoaded;
  float mjj_dn_;
  TBranch *mjj_dn_branch;
  bool mjj_dn_isLoaded;
  vector<float> *weightsf_lepconv_;
  TBranch *weightsf_lepconv_branch;
  bool weightsf_lepconv_isLoaded;
  vector<float> *gamma_phi_;
  TBranch *gamma_phi_branch;
  bool gamma_phi_isLoaded;
  float phpfcands_0013_phi_;
  TBranch *phpfcands_0013_phi_branch;
  bool phpfcands_0013_phi_isLoaded;
  float nupfcands_1624_pt_;
  TBranch *nupfcands_1624_pt_branch;
  bool nupfcands_1624_pt_isLoaded;
  int HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8_;
  TBranch *HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8_branch;
  bool HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8_isLoaded;
  vector<float> *gamma_sigmaIetaIeta_;
  TBranch *gamma_sigmaIetaIeta_branch;
  bool gamma_sigmaIetaIeta_isLoaded;
  int Flag_globalTightHalo2016_;
  TBranch *Flag_globalTightHalo2016_branch;
  bool Flag_globalTightHalo2016_isLoaded;
  int mass_chi_;
  TBranch *mass_chi_branch;
  bool mass_chi_isLoaded;
  vector<bool> *isotrack_isLostTrack_;
  TBranch *isotrack_isLostTrack_branch;
  bool isotrack_isLostTrack_isLoaded;
  int nBJetMedium35_;
  TBranch *nBJetMedium35_branch;
  bool nBJetMedium35_isLoaded;
  int nisoTrack_PFLep5_woverlaps_;
  TBranch *nisoTrack_PFLep5_woverlaps_branch;
  bool nisoTrack_PFLep5_woverlaps_isLoaded;
  int nBJetTight25_up_;
  TBranch *nBJetTight25_up_branch;
  bool nBJetTight25_up_isLoaded;
  vector<float> *gamma_neuHadIso_;
  TBranch *gamma_neuHadIso_branch;
  bool gamma_neuHadIso_isLoaded;
  int Flag_badMuonFilter_;
  TBranch *Flag_badMuonFilter_branch;
  bool Flag_badMuonFilter_isLoaded;
  float matched_emf_;
  TBranch *matched_emf_branch;
  bool matched_emf_isLoaded;
  vector<float> *lep_dxy_;
  TBranch *lep_dxy_branch;
  bool lep_dxy_isLoaded;
  float chpfcands_1316_pt_;
  TBranch *chpfcands_1316_pt_branch;
  bool chpfcands_1316_pt_isLoaded;
  vector<int> *genPart_pdgId_;
  TBranch *genPart_pdgId_branch;
  bool genPart_pdgId_isLoaded;
  vector<int> *jets_mcFlavour_;
  TBranch *jets_mcFlavour_branch;
  bool jets_mcFlavour_isLoaded;
  int nveto_leptons_;
  TBranch *nveto_leptons_branch;
  bool nveto_leptons_isLoaded;
  float sum_mlb_up_;
  TBranch *sum_mlb_up_branch;
  bool sum_mlb_up_isLoaded;
  float nupfcands_1316_pt_;
  TBranch *nupfcands_1316_pt_branch;
  bool nupfcands_1316_pt_isLoaded;
  int ngamma_;
  TBranch *ngamma_branch;
  bool ngamma_isLoaded;
  vector<float> *lep_relIso03MREA_;
  TBranch *lep_relIso03MREA_branch;
  bool lep_relIso03MREA_isLoaded;
  float mjj_mindphi_dn_;
  TBranch *mjj_mindphi_dn_branch;
  bool mjj_mindphi_dn_isLoaded;
  float dphi_jj_dn_;
  TBranch *dphi_jj_dn_branch;
  bool dphi_jj_dn_isLoaded;
  float mt2_dn_;
  TBranch *mt2_dn_branch;
  bool mt2_dn_isLoaded;
  float metsig_unofficial_up_;
  TBranch *metsig_unofficial_up_branch;
  bool metsig_unofficial_up_isLoaded;
  float rho25_;
  TBranch *rho25_branch;
  bool rho25_isLoaded;
  int nisoTrack_PFMu5_woverlaps_;
  TBranch *nisoTrack_PFMu5_woverlaps_branch;
  bool nisoTrack_PFMu5_woverlaps_isLoaded;
  float chpfcands_1624_phi_;
  TBranch *chpfcands_1624_phi_branch;
  bool chpfcands_1624_phi_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *ak8jets_p4_;
  TBranch *ak8jets_p4_branch;
  bool ak8jets_p4_isLoaded;
  int HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_;
  TBranch *HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_branch;
  bool HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_isLoaded;
  float mt2b_up_;
  TBranch *mt2b_up_branch;
  bool mt2b_up_isLoaded;
  vector<int> *genLep_motherId_;
  TBranch *genLep_motherId_branch;
  bool genLep_motherId_isLoaded;
  float ht_up_;
  TBranch *ht_up_branch;
  bool ht_up_isLoaded;
  vector<float> *weightsf_lepreco_;
  TBranch *weightsf_lepreco_branch;
  bool weightsf_lepreco_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_p4_;
  TBranch *jets_p4_branch;
  bool jets_p4_isLoaded;
  float phpfcands_1316_sumet_;
  TBranch *phpfcands_1316_sumet_branch;
  bool phpfcands_1316_sumet_isLoaded;
  float met_rawPhi_;
  TBranch *met_rawPhi_branch;
  bool met_rawPhi_isLoaded;
  vector<float> *lep_glb_pterrOpt_;
  TBranch *lep_glb_pterrOpt_branch;
  bool lep_glb_pterrOpt_isLoaded;
  vector<bool> *genPart_isPromptFinalState_;
  TBranch *genPart_isPromptFinalState_branch;
  bool genPart_isPromptFinalState_isLoaded;
  float dphi_metj2_;
  TBranch *dphi_metj2_branch;
  bool dphi_metj2_isLoaded;
  float dphi_metj3_;
  TBranch *dphi_metj3_branch;
  bool dphi_metj3_isLoaded;
  float dphi_metj1_;
  TBranch *dphi_metj1_branch;
  bool dphi_metj1_isLoaded;
  vector<float> *genLep_phi_;
  TBranch *genLep_phi_branch;
  bool genLep_phi_isLoaded;
  float phpfcands_1316_pt_;
  TBranch *phpfcands_1316_pt_branch;
  bool phpfcands_1316_pt_isLoaded;
  float dilmass_;
  TBranch *dilmass_branch;
  bool dilmass_isLoaded;
  float isrboost_;
  TBranch *isrboost_branch;
  bool isrboost_isLoaded;
  int nBJetTight35_up_;
  TBranch *nBJetTight35_up_branch;
  bool nBJetTight35_up_isLoaded;
  int ngenTau_;
  TBranch *ngenTau_branch;
  bool ngenTau_isLoaded;
  float dphi_ll_dn_;
  TBranch *dphi_ll_dn_branch;
  bool dphi_ll_dn_isLoaded;
  int njets_up_;
  TBranch *njets_up_branch;
  bool njets_up_isLoaded;
  vector<float> *lep_relIso03MRNC_;
  TBranch *lep_relIso03MRNC_branch;
  bool lep_relIso03MRNC_isLoaded;
  float chpfcands_2430_phi_;
  TBranch *chpfcands_2430_phi_branch;
  bool chpfcands_2430_phi_isLoaded;
  vector<int> *highPtPFcands_pdgId_;
  TBranch *highPtPFcands_pdgId_branch;
  bool highPtPFcands_pdgId_isLoaded;
  int nhighPtPFcands_;
  TBranch *nhighPtPFcands_branch;
  bool nhighPtPFcands_isLoaded;
  float met_T1CHS_miniAOD_CORE_up_pt_;
  TBranch *met_T1CHS_miniAOD_CORE_up_pt_branch;
  bool met_T1CHS_miniAOD_CORE_up_pt_isLoaded;
  float chpfcands_30in_sumet_;
  TBranch *chpfcands_30in_sumet_branch;
  bool chpfcands_30in_sumet_isLoaded;
  int nBadMuons20_;
  TBranch *nBadMuons20_branch;
  bool nBadMuons20_isLoaded;
  int HLT_DoubleEle25_CaloIdL_MW_;
  TBranch *HLT_DoubleEle25_CaloIdL_MW_branch;
  bool HLT_DoubleEle25_CaloIdL_MW_isLoaded;
  int HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_;
  TBranch *HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_branch;
  bool HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_isLoaded;
  int HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_;
  TBranch *HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_branch;
  bool HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_isLoaded;
  float nupfcands_1624_phi_;
  TBranch *nupfcands_1624_phi_branch;
  bool nupfcands_1624_phi_isLoaded;
  vector<float> *gamma_r9_;
  TBranch *gamma_r9_branch;
  bool gamma_r9_isLoaded;
  float chpfcands_0013_sumet_;
  TBranch *chpfcands_0013_sumet_branch;
  bool chpfcands_0013_sumet_isLoaded;
  int Flag_ecalLaserCorrFilter_;
  TBranch *Flag_ecalLaserCorrFilter_branch;
  bool Flag_ecalLaserCorrFilter_isLoaded;
  float weight_btagsf_heavy_UP_;
  TBranch *weight_btagsf_heavy_UP_branch;
  bool weight_btagsf_heavy_UP_isLoaded;
  vector<float> *gamma_genIso_;
  TBranch *gamma_genIso_branch;
  bool gamma_genIso_isLoaded;
  int Flag_badMuons_;
  TBranch *Flag_badMuons_branch;
  bool Flag_badMuons_isLoaded;
  float metsig_unofficial_;
  TBranch *metsig_unofficial_branch;
  bool metsig_unofficial_isLoaded;
  int HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_;
  TBranch *HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_branch;
  bool HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_isLoaded;
  vector<float> *ak8jets_softDropMass_;
  TBranch *ak8jets_softDropMass_branch;
  bool ak8jets_softDropMass_isLoaded;
  vector<float> *lep_eta_;
  TBranch *lep_eta_branch;
  bool lep_eta_isLoaded;
  vector<int> *genPart_status_;
  TBranch *genPart_status_branch;
  bool genPart_status_isLoaded;
  vector<float> *weightsf_lepconv_FS_;
  TBranch *weightsf_lepconv_FS_branch;
  bool weightsf_lepconv_FS_isLoaded;
  int nBJetMedium25_dn_;
  TBranch *nBJetMedium25_dn_branch;
  bool nBJetMedium25_dn_isLoaded;
  float puWeight_;
  TBranch *puWeight_branch;
  bool puWeight_isLoaded;
  float met_pt_;
  TBranch *met_pt_branch;
  bool met_pt_isLoaded;
  float weight_btagsf_light_UP_;
  TBranch *weight_btagsf_light_UP_branch;
  bool weight_btagsf_light_UP_isLoaded;
  int HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_;
  TBranch *HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_branch;
  bool HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_isLoaded;
  float nupfcands_0013_phi_;
  TBranch *nupfcands_0013_phi_branch;
  bool nupfcands_0013_phi_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *lep_p4_;
  TBranch *lep_p4_branch;
  bool lep_p4_isLoaded;
  vector<bool> *genLep_isp6status3_;
  TBranch *genLep_isp6status3_branch;
  bool genLep_isp6status3_isLoaded;
  vector<float> *weightsf_lepiso_FS_;
  TBranch *weightsf_lepiso_FS_branch;
  bool weightsf_lepiso_FS_isLoaded;
  float mbb_bpt_;
  TBranch *mbb_bpt_branch;
  bool mbb_bpt_isLoaded;
  vector<int> *genLep_status_;
  TBranch *genLep_status_branch;
  bool genLep_status_isLoaded;
  vector<int> *gamma_genIsPromptFinalState_;
  TBranch *gamma_genIsPromptFinalState_branch;
  bool gamma_genIsPromptFinalState_isLoaded;
  float mbb_csv_;
  TBranch *mbb_csv_branch;
  bool mbb_csv_isLoaded;
  float weight_L1prefire_;
  TBranch *weight_L1prefire_branch;
  bool weight_L1prefire_isLoaded;
  float mbb_csv_dn_;
  TBranch *mbb_csv_dn_branch;
  bool mbb_csv_dn_isLoaded;
  vector<float> *genLepFromTau_pt_;
  TBranch *genLepFromTau_pt_branch;
  bool genLepFromTau_pt_isLoaded;
  int nGammas20_;
  TBranch *nGammas20_branch;
  bool nGammas20_isLoaded;
  bool evt_passgoodrunlist_;
  TBranch *evt_passgoodrunlist_branch;
  bool evt_passgoodrunlist_isLoaded;
  float mt2b_;
  TBranch *mt2b_branch;
  bool mt2b_isLoaded;
  float mt2j_;
  TBranch *mt2j_branch;
  bool mt2j_isLoaded;
  float met_T1CHS_miniAOD_CORE_dn_pt_;
  TBranch *met_T1CHS_miniAOD_CORE_dn_pt_branch;
  bool met_T1CHS_miniAOD_CORE_dn_pt_isLoaded;
  int HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_;
  TBranch *HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_branch;
  bool HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *isotrack_p4_;
  TBranch *isotrack_p4_branch;
  bool isotrack_p4_isLoaded;
  int HLT_Photon120_R9Id90_HE10_IsoM_;
  TBranch *HLT_Photon120_R9Id90_HE10_IsoM_branch;
  bool HLT_Photon120_R9Id90_HE10_IsoM_isLoaded;
  int Flag_globalSuperTightHalo2016_;
  TBranch *Flag_globalSuperTightHalo2016_branch;
  bool Flag_globalSuperTightHalo2016_isLoaded;
  float weight_btagsf_;
  TBranch *weight_btagsf_branch;
  bool weight_btagsf_isLoaded;
  int HLT_Photon110EB_TightID_TightIso_;
  TBranch *HLT_Photon110EB_TightID_TightIso_branch;
  bool HLT_Photon110EB_TightID_TightIso_isLoaded;
  vector<float> *genPart_charge_;
  TBranch *genPart_charge_branch;
  bool genPart_charge_isLoaded;
  float met_miniaod_phi_;
  TBranch *met_miniaod_phi_branch;
  bool met_miniaod_phi_isLoaded;
  vector<float> *jets_dn_csv_;
  TBranch *jets_dn_csv_branch;
  bool jets_dn_csv_isLoaded;
  float mt2b_genmet_;
  TBranch *mt2b_genmet_branch;
  bool mt2b_genmet_isLoaded;
  vector<float> *lep_mass_;
  TBranch *lep_mass_branch;
  bool lep_mass_isLoaded;
  int nisoTrack_PFHad10_woverlaps_;
  TBranch *nisoTrack_PFHad10_woverlaps_branch;
  bool nisoTrack_PFHad10_woverlaps_isLoaded;
  float mt_lep1_;
  TBranch *mt_lep1_branch;
  bool mt_lep1_isLoaded;
  float phpfcands_1624_phi_;
  TBranch *phpfcands_1624_phi_branch;
  bool phpfcands_1624_phi_isLoaded;
  float phpfcands_1624_pt_;
  TBranch *phpfcands_1624_pt_branch;
  bool phpfcands_1624_pt_isLoaded;
  float matched_neutralemf_;
  TBranch *matched_neutralemf_branch;
  bool matched_neutralemf_isLoaded;
  float mt2b_dn_;
  TBranch *mt2b_dn_branch;
  bool mt2b_dn_isLoaded;
  float phpfcands_2430_sumet_;
  TBranch *phpfcands_2430_sumet_branch;
  bool phpfcands_2430_sumet_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_medb_dn_p4_;
  TBranch *jets_medb_dn_p4_branch;
  bool jets_medb_dn_p4_isLoaded;
  float dR_jj_up_;
  TBranch *dR_jj_up_branch;
  bool dR_jj_up_isLoaded;
  vector<int> *lep_mcMatchId_;
  TBranch *lep_mcMatchId_branch;
  bool lep_mcMatchId_isLoaded;
  float chpfcands_1316_phi_;
  TBranch *chpfcands_1316_phi_branch;
  bool chpfcands_1316_phi_isLoaded;
  vector<float> *genTau_eta_;
  TBranch *genTau_eta_branch;
  bool genTau_eta_isLoaded;
  float nupfcands_2430_pt_;
  TBranch *nupfcands_2430_pt_branch;
  bool nupfcands_2430_pt_isLoaded;
  vector<int> *genPart_motherId_;
  TBranch *genPart_motherId_branch;
  bool genPart_motherId_isLoaded;
  int nBJetTight35_;
  TBranch *nBJetTight35_branch;
  bool nBJetTight35_isLoaded;
  int HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_isLoaded;
  float evt_xsec_;
  TBranch *evt_xsec_branch;
  bool evt_xsec_isLoaded;
  vector<int> *lep_convVeto_;
  TBranch *lep_convVeto_branch;
  bool lep_convVeto_isLoaded;
  vector<float> *lep_validfraction_;
  TBranch *lep_validfraction_branch;
  bool lep_validfraction_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_up_p4_;
  TBranch *jets_up_p4_branch;
  bool jets_up_p4_isLoaded;
  float chpfcands_1316_sumet_;
  TBranch *chpfcands_1316_sumet_branch;
  bool chpfcands_1316_sumet_isLoaded;
  int run_;
  TBranch *run_branch;
  bool run_isLoaded;
  float chpfcands_1624_pt_;
  TBranch *chpfcands_1624_pt_branch;
  bool chpfcands_1624_pt_isLoaded;
  vector<int> *genLepFromTau_pdgId_;
  TBranch *genLepFromTau_pdgId_branch;
  bool genLepFromTau_pdgId_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_medb_up_p4_;
  TBranch *jets_medb_up_p4_branch;
  bool jets_medb_up_p4_isLoaded;
  vector<float> *gamma_hcpfclusiso_;
  TBranch *gamma_hcpfclusiso_branch;
  bool gamma_hcpfclusiso_isLoaded;
  bool HLT_Photon75_R9Id90_HE10_IsoM_matchedtophoton_;
  TBranch *HLT_Photon75_R9Id90_HE10_IsoM_matchedtophoton_branch;
  bool HLT_Photon75_R9Id90_HE10_IsoM_matchedtophoton_isLoaded;
  float met_T1CHS_miniAOD_CORE_pt_;
  TBranch *met_T1CHS_miniAOD_CORE_pt_branch;
  bool met_T1CHS_miniAOD_CORE_pt_isLoaded;
  int HLT_Photon50_R9Id90_HE10_IsoM_;
  TBranch *HLT_Photon50_R9Id90_HE10_IsoM_branch;
  bool HLT_Photon50_R9Id90_HE10_IsoM_isLoaded;
  float dphi_jj_up_;
  TBranch *dphi_jj_up_branch;
  bool dphi_jj_up_isLoaded;
  vector<float> *gamma_chHadIso_;
  TBranch *gamma_chHadIso_branch;
  bool gamma_chHadIso_isLoaded;
  int nTrueInt_;
  TBranch *nTrueInt_branch;
  bool nTrueInt_isLoaded;
  float dphi_ll_;
  TBranch *dphi_ll_branch;
  bool dphi_ll_isLoaded;
  vector<float> *lep_relIsoUncorr_;
  TBranch *lep_relIsoUncorr_branch;
  bool lep_relIsoUncorr_isLoaded;
  int Flag_trackingFailureFilter_;
  TBranch *Flag_trackingFailureFilter_branch;
  bool Flag_trackingFailureFilter_isLoaded;
  int Flag_goodVertices_;
  TBranch *Flag_goodVertices_branch;
  bool Flag_goodVertices_isLoaded;
  float decayedphoton_mt2_;
  TBranch *decayedphoton_mt2_branch;
  bool decayedphoton_mt2_isLoaded;
  float chpfcands_1624_sumet_;
  TBranch *chpfcands_1624_sumet_branch;
  bool chpfcands_1624_sumet_isLoaded;
  int HLT_Photon200_;
  TBranch *HLT_Photon200_branch;
  bool HLT_Photon200_isLoaded;
  int HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_;
  TBranch *HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_branch;
  bool HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_isLoaded;
  int HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_isLoaded;
  int hyp_type_;
  TBranch *hyp_type_branch;
  bool hyp_type_isLoaded;
  vector<int> *genLep_sourceId_;
  TBranch *genLep_sourceId_branch;
  bool genLep_sourceId_isLoaded;
  int nElectrons10_;
  TBranch *nElectrons10_branch;
  bool nElectrons10_isLoaded;
  float mt2_;
  TBranch *mt2_branch;
  bool mt2_isLoaded;
  float dphi_ll_up_;
  TBranch *dphi_ll_up_branch;
  bool dphi_ll_up_isLoaded;
  int HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW_;
  TBranch *HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW_branch;
  bool HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW_isLoaded;
  int HLT_Photon90_R9Id90_HE10_IsoM_;
  TBranch *HLT_Photon90_R9Id90_HE10_IsoM_branch;
  bool HLT_Photon90_R9Id90_HE10_IsoM_isLoaded;
  float ht_;
  TBranch *ht_branch;
  bool ht_isLoaded;
  float met_T1CHS_fromCORE_phi_;
  TBranch *met_T1CHS_fromCORE_phi_branch;
  bool met_T1CHS_fromCORE_phi_isLoaded;
  int nBJetTight35_dn_;
  TBranch *nBJetTight35_dn_branch;
  bool nBJetTight35_dn_isLoaded;
  vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *highPtPFcands_p4_;
  TBranch *highPtPFcands_p4_branch;
  bool highPtPFcands_p4_isLoaded;
  float nupfcands_30in_pt_;
  TBranch *nupfcands_30in_pt_branch;
  bool nupfcands_30in_pt_isLoaded;
  int isData_;
  TBranch *isData_branch;
  bool isData_isLoaded;
  vector<float> *genLep_charge_;
  TBranch *genLep_charge_branch;
  bool genLep_charge_isLoaded;
  float weight_btagsf_light_DN_;
  TBranch *weight_btagsf_light_DN_branch;
  bool weight_btagsf_light_DN_isLoaded;
  vector<float> *gamma_hollowtkiso03_;
  TBranch *gamma_hollowtkiso03_branch;
  bool gamma_hollowtkiso03_isLoaded;
  int ngenPart_;
  TBranch *ngenPart_branch;
  bool ngenPart_isLoaded;
  float dilpt_;
  TBranch *dilpt_branch;
  bool dilpt_isLoaded;
  vector<float> *genLepFromTau_mass_;
  TBranch *genLepFromTau_mass_branch;
  bool genLepFromTau_mass_isLoaded;
  vector<float> *weightsf_lepip_;
  TBranch *weightsf_lepip_branch;
  bool weightsf_lepip_isLoaded;
  float mbb_csv_up_;
  TBranch *mbb_csv_up_branch;
  bool mbb_csv_up_isLoaded;
  bool HLT_Photon36_R9Id90_HE10_IsoM_matchedtophoton_;
  TBranch *HLT_Photon36_R9Id90_HE10_IsoM_matchedtophoton_branch;
  bool HLT_Photon36_R9Id90_HE10_IsoM_matchedtophoton_isLoaded;
  float met_genPt_;
  TBranch *met_genPt_branch;
  bool met_genPt_isLoaded;
  vector<float> *lep_sta_pterrOpt_;
  TBranch *lep_sta_pterrOpt_branch;
  bool lep_sta_pterrOpt_isLoaded;
  vector<int> *genLep_pdgId_;
  TBranch *genLep_pdgId_branch;
  bool genLep_pdgId_isLoaded;
  vector<float> *weightsf_lepid_;
  TBranch *weightsf_lepid_branch;
  bool weightsf_lepid_isLoaded;
  vector<float> *gamma_drMinParton_;
  TBranch *gamma_drMinParton_branch;
  bool gamma_drMinParton_isLoaded;
  float phpfcands_0013_pt_;
  TBranch *phpfcands_0013_pt_branch;
  bool phpfcands_0013_pt_isLoaded;
  vector<int> *genPart_grandmaId_;
  TBranch *genPart_grandmaId_branch;
  bool genPart_grandmaId_isLoaded;
  int HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_;
  TBranch *HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_branch;
  bool HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_isLoaded;
  float deta_jj_up_;
  TBranch *deta_jj_up_branch;
  bool deta_jj_up_isLoaded;
  vector<float> *genTau_charge_;
  TBranch *genTau_charge_branch;
  bool genTau_charge_isLoaded;
  vector<float> *jets_muf_;
  TBranch *jets_muf_branch;
  bool jets_muf_isLoaded;
  int HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_isLoaded;
  float isr_weight_;
  TBranch *isr_weight_branch;
  bool isr_weight_isLoaded;
  vector<int> *jets_mcHadronFlav_;
  TBranch *jets_mcHadronFlav_branch;
  bool jets_mcHadronFlav_isLoaded;
  vector<int> *genTau_pdgId_;
  TBranch *genTau_pdgId_branch;
  bool genTau_pdgId_isLoaded;
  int HLT_Photon22_R9Id90_HE10_IsoM_;
  TBranch *HLT_Photon22_R9Id90_HE10_IsoM_branch;
  bool HLT_Photon22_R9Id90_HE10_IsoM_isLoaded;
  int nVert_;
  TBranch *nVert_branch;
  bool nVert_isLoaded;
  vector<float> *gamma_hOverE_;
  TBranch *gamma_hOverE_branch;
  bool gamma_hOverE_isLoaded;
  vector<float> *genPart_eta_;
  TBranch *genPart_eta_branch;
  bool genPart_eta_isLoaded;
  float evt_filter_;
  TBranch *evt_filter_branch;
  bool evt_filter_isLoaded;
  int Flag_duplicateMuons_;
  TBranch *Flag_duplicateMuons_branch;
  bool Flag_duplicateMuons_isLoaded;
  bool HLT_Photon90_R9Id90_HE10_IsoM_matchedtophoton_;
  TBranch *HLT_Photon90_R9Id90_HE10_IsoM_matchedtophoton_branch;
  bool HLT_Photon90_R9Id90_HE10_IsoM_matchedtophoton_isLoaded;
  float sumet_raw_;
  TBranch *sumet_raw_branch;
  bool sumet_raw_isLoaded;
  int Flag_CSCTightHalo2015Filter_;
  TBranch *Flag_CSCTightHalo2015Filter_branch;
  bool Flag_CSCTightHalo2015Filter_isLoaded;
public:
  void Init(TTree *tree);
  void GetEntry(unsigned int idx);
  void LoadAllBranches();
  const int &HLT_Mu37_Ele27_CaloIdL_MW();
  const vector<float> &ak8jets_tau1();
  const vector<float> &ak8jets_tau3();
  const vector<float> &ak8jets_tau2();
  const int &HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZ();
  const int &HLT_Mu27_TkMu8();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genPart_p4();
  const int &HLT_Mu50();
  const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL();
  const int &HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &nisoTrack_5gev();
  const float &nupfcands_2430_phi();
  const int &Flag_badMuonFilterv2();
  const vector<float> &isotrack_absiso();
  const float &phpfcands_2430_phi();
  const int &HLT_IsoMu27();
  const vector<float> &genPart_pt();
  const float &isr_unc();
  const float &sum_mlb();
  const float &met_miniaod_pt();
  const vector<int> &lep_charge();
  const int &nlep();
  const float &met_genPhi();
  const float &phpfcands_0013_sumet();
  const vector<int> &lep_lostHits();
  const unsigned long long &evt();
  const vector<int> &gamma_idCutBased();
  const vector<int> &genLepFromTau_status();
  const float &dphi_genmetj1();
  const int &njets();
  const int &mass_LSP();
  const vector<float> &weightsf_lepip_FS();
  const vector<float> &genTau_phi();
  const vector<int> &ak8jets_parton_flavor();
  const int &HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL();
  const float &nupfcands_1316_sumet();
  const vector<float> &jets_csv();
  const float &dphi_metj2_dn();
  const int &Flag_eeBadScFilter();
  const vector<float> &jets_up_csv();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &decayedphoton_bosn_p4();
  const float &dR_jj_dn();
  const vector<int> &genLep_motherIndex();
  const vector<float> &gamma_phIso();
  const vector<float> &lep_etaSC();
  const vector<float> &lep_MVA();
  const int &nBJetTight25();
  const int &nBJetMedium35_dn();
  const int &nTaus20();
  const float &met_T1CHS_miniAOD_CORE_dn_phi();
  const float &phpfcands_30in_sumet();
  const vector<float> &lep_phi();
  const float &met_T1CHS_fromCORE_pt();
  const float &sum_mlb_dn();
  const vector<float> &genPart_mass();
  const bool &HLT_Photon120_R9Id90_HE10_IsoM_matchedtophoton();
  const vector<float> &genLepFromTau_charge();
  const int &evt_nEvts();
  const bool &HLT_Photon165_HE10_matchedtophoton();
  const float &met_calo_pt();
  const float &gen_ht();
  const int &HLT_Mu30_TkMu11();
  const float &deta_jj_dn();
  const int &nBJetLoose25();
  const bool &HLT_Photon50_R9Id90_HE10_IsoM_matchedtophoton();
  const vector<float> &gamma_mass();
  const float &evt_scale1fb();
  const float &met_calo_phi();
  const int &HLT_Mu27_Ele37_CaloIdL_MW();
  const float &phpfcands_2430_pt();
  const float &mjj_mindphi();
  const vector<float> &genTau_mass();
  const int &nJet200MuFrac50DphiMet();
  const vector<float> &genLepFromTau_phi();
  const float &chpfcands_2430_sumet();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &decayedphoton_lep1_p4();
  const vector<float> &genLep_pt();
  const vector<float> &gamma_hOverE_online();
  const int &HLT_singleMu_noiso();
  const float &mbb_bpt_dn();
  const bool &HLT_Photon165_R9Id90_HE10_IsoM_matchedtophoton();
  const float &met_T1CHS_miniAOD_CORE_phi();
  const float &nupfcands_2430_sumet();
  const int &HLT_singleMu();
  const float &mt2_genmet();
  const float &phpfcands_30in_phi();
  const float &nupfcands_1624_sumet();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_dn_p4();
  const float &phpfcands_1316_phi();
  const int &nisoTrack_mt2();
  const float &chpfcands_30in_pt();
  const int &nisoTrack_PFEle5_woverlaps();
  const float &nupfcands_30in_phi();
  const vector<int> &lep_tightCharge();
  const int &nBJetLoose35();
  const int &Flag_HBHEIsoNoiseFilter();
  const int &HLT_Photon30_R9Id90_HE10_IsoM();
  const vector<float> &lep_glb_x2ondof();
  const vector<int> &genLepFromTau_sourceId();
  const float &met_rawPt();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &decayedphoton_lep2_p4();
  const float &met_muegclean_pt();
  const int &HLT_Mu30_Ele30_CaloIdL_GsfTrkIdVL();
  const float &met_T1CHS_pt();
  const float &dphi_metj1_up();
  const int &lumi();
  const bool &elveto();
  const int &HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ();
  const float &chpfcands_30in_phi();
  const float &mjj();
  const float &chpfcands_0013_pt();
  const vector<int> &lep_pdgId();
  const bool &HLT_Photon30_R9Id90_HE10_IsoM_matchedtophoton();
  const vector<float> &lep_relIso03();
  const vector<float> &lep_relIso04();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gamma_p4();
  const int &Flag_EcalDeadCellTriggerPrimitiveFilter();
  const bool &HLT_Photon22_R9Id90_HE10_IsoM_matchedtophoton();
  const int &nBJetMedium25();
  const int &nBJetLoose25_dn();
  const vector<float> &lep_pt();
  const float &weight_L1prefire_down();
  const int &nBJetTight25_dn();
  const vector<float> &gamma_pt();
  const vector<float> &highPtPFcands_dz();
  const vector<float> &weightsf_lepid_FS();
  const vector<int> &genTau_sourceId();
  const float &chpfcands_0013_phi();
  const int &Flag_hcalLaserEventFilter();
  const int &HLT_Photon165_R9Id90_HE10_IsoM();
  const float &chpfcands_2430_pt();
  const float &dphi_jj();
  const int &nBJetLoose35_up();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_p4();
  const vector<int> &gamma_mcMatchId();
  const float &nupfcands_1316_phi();
  const float &met_muegclean_phi();
  const vector<bool> &genPart_isp6status3();
  const vector<float> &lep_x2ondof();
  const float &ht_dn();
  const int &ngenLep();
  const int &year();
  const int &HLT_DoubleEle27_CaloIdL_MW_Edge();
  const vector<float> &genLepFromTau_eta();
  const int &HLT_ECALHT800_NoJetID();
  const vector<float> &gamma_genPt();
  const float &mt2_up();
  const float &mjj_up();
  const vector<unsigned long> &isotrack_index();
  const float &nupfcands_0013_sumet();
  const float &dphi_metj2_up();
  const float &dphi_metj3_up();
  const vector<int> &isotrack_pdgId();
  const float &evt_kfactor();
  const int &nBJetMedium35_up();
  const int &HLT_CaloJet500_NoJetID();
  const vector<float> &lep_relIso03MRDB();
  const int &ngenLepFromTau();
  const float &dphi_genmetj3();
  const float &dphi_metj3_dn();
  const int &HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass8();
  const int &HLT_singleEl();
  const int &HLT_Photon75_R9Id90_HE10_IsoM();
  const float &dRll();
  const int &njets_dn();
  const int &isr_njets();
  const vector<float> &gamma_ecpfclusiso();
  const float &weight_L1prefire_up();
  const float &phpfcands_30in_pt();
  const int &HLT_Photon165_HE10();
  const float &nupfcands_0013_pt();
  const vector<float> &genLep_eta();
  const int &nJetFailId();
  const int &Flag_HBHENoiseFilter();
  const float &deta_jj();
  const float &metsig_unofficial_dn();
  const float &dR_jj();
  const int &nFatJets();
  const int &HLT_Mu37_TkMu27();
  const float &nupfcands_30in_sumet();
  const float &mjj_mindphi_up();
  const int &nBJetLoose35_dn();
  const float &mbb_bpt_up();
  const vector<float> &genTau_pt();
  const int &Flag_noBadMuons();
  const vector<float> &lep_dz();
  const vector<float> &gamma_eta();
  const vector<float> &genPart_phi();
  const vector<float> &weightsf_lepiso();
  const int &Flag_CSCTightHaloFilter();
  const int &nBJetLoose25_up();
  const int &HLT_Mu33_Ele33_CaloIdL_GsfTrkIdVL();
  const vector<int> &lep_tightId();
  const int &nBJetMedium25_up();
  const float &met_T1CHS_miniAOD_CORE_up_phi();
  const float &phpfcands_1624_sumet();
  const int &HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL();
  const float &met_phi();
  const vector<int> &genTau_status();
  const vector<float> &genLep_mass();
  const float &met_T1CHS_phi();
  const float &rho();
  const float &dphi_metj1_dn();
  const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ();
  const int &mass_gluino();
  const int &HLT_DoubleEle33_CaloIdL_MW();
  const vector<TString> &evt_dataset();
  const vector<float> &lep_pterr();
  const float &weight_btagsf_heavy_DN();
  const int &Flag_badChargedCandidateFilter();
  const int &Flag_badChargedCandidateFilterv2();
  const vector<float> &lep_sta_x2ondof();
  const float &dphi_genmetj2();
  const int &nMuons10();
  const int &evt_type();
  const int &HLT_Photon36_R9Id90_HE10_IsoM();
  const float &mjj_dn();
  const vector<float> &weightsf_lepconv();
  const vector<float> &gamma_phi();
  const float &phpfcands_0013_phi();
  const float &nupfcands_1624_pt();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8();
  const vector<float> &gamma_sigmaIetaIeta();
  const int &Flag_globalTightHalo2016();
  const int &mass_chi();
  const vector<bool> &isotrack_isLostTrack();
  const int &nBJetMedium35();
  const int &nisoTrack_PFLep5_woverlaps();
  const int &nBJetTight25_up();
  const vector<float> &gamma_neuHadIso();
  const int &Flag_badMuonFilter();
  const float &matched_emf();
  const vector<float> &lep_dxy();
  const float &chpfcands_1316_pt();
  const vector<int> &genPart_pdgId();
  const vector<int> &jets_mcFlavour();
  const int &nveto_leptons();
  const float &sum_mlb_up();
  const float &nupfcands_1316_pt();
  const int &ngamma();
  const vector<float> &lep_relIso03MREA();
  const float &mjj_mindphi_dn();
  const float &dphi_jj_dn();
  const float &mt2_dn();
  const float &metsig_unofficial_up();
  const float &rho25();
  const int &nisoTrack_PFMu5_woverlaps();
  const float &chpfcands_1624_phi();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &ak8jets_p4();
  const int &HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ();
  const float &mt2b_up();
  const vector<int> &genLep_motherId();
  const float &ht_up();
  const vector<float> &weightsf_lepreco();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_p4();
  const float &phpfcands_1316_sumet();
  const float &met_rawPhi();
  const vector<float> &lep_glb_pterrOpt();
  const vector<bool> &genPart_isPromptFinalState();
  const float &dphi_metj2();
  const float &dphi_metj3();
  const float &dphi_metj1();
  const vector<float> &genLep_phi();
  const float &phpfcands_1316_pt();
  const float &dilmass();
  const float &isrboost();
  const int &nBJetTight35_up();
  const int &ngenTau();
  const float &dphi_ll_dn();
  const int &njets_up();
  const vector<float> &lep_relIso03MRNC();
  const float &chpfcands_2430_phi();
  const vector<int> &highPtPFcands_pdgId();
  const int &nhighPtPFcands();
  const float &met_T1CHS_miniAOD_CORE_up_pt();
  const float &chpfcands_30in_sumet();
  const int &nBadMuons20();
  const int &HLT_DoubleEle25_CaloIdL_MW();
  const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ();
  const float &nupfcands_1624_phi();
  const vector<float> &gamma_r9();
  const float &chpfcands_0013_sumet();
  const int &Flag_ecalLaserCorrFilter();
  const float &weight_btagsf_heavy_UP();
  const vector<float> &gamma_genIso();
  const int &Flag_badMuons();
  const float &metsig_unofficial();
  const int &HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ();
  const vector<float> &ak8jets_softDropMass();
  const vector<float> &lep_eta();
  const vector<int> &genPart_status();
  const vector<float> &weightsf_lepconv_FS();
  const int &nBJetMedium25_dn();
  const float &puWeight();
  const float &met_pt();
  const float &weight_btagsf_light_UP();
  const int &HLT_DoubleEle33_CaloIdL_GsfTrkIdVL();
  const float &nupfcands_0013_phi();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &lep_p4();
  const vector<bool> &genLep_isp6status3();
  const vector<float> &weightsf_lepiso_FS();
  const float &mbb_bpt();
  const vector<int> &genLep_status();
  const vector<int> &gamma_genIsPromptFinalState();
  const float &mbb_csv();
  const float &weight_L1prefire();
  const float &mbb_csv_dn();
  const vector<float> &genLepFromTau_pt();
  const int &nGammas20();
  const bool &evt_passgoodrunlist();
  const float &mt2b();
  const float &mt2j();
  const float &met_T1CHS_miniAOD_CORE_dn_pt();
  const int &HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &isotrack_p4();
  const int &HLT_Photon120_R9Id90_HE10_IsoM();
  const int &Flag_globalSuperTightHalo2016();
  const float &weight_btagsf();
  const int &HLT_Photon110EB_TightID_TightIso();
  const vector<float> &genPart_charge();
  const float &met_miniaod_phi();
  const vector<float> &jets_dn_csv();
  const float &mt2b_genmet();
  const vector<float> &lep_mass();
  const int &nisoTrack_PFHad10_woverlaps();
  const float &mt_lep1();
  const float &phpfcands_1624_phi();
  const float &phpfcands_1624_pt();
  const float &matched_neutralemf();
  const float &mt2b_dn();
  const float &phpfcands_2430_sumet();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_dn_p4();
  const float &dR_jj_up();
  const vector<int> &lep_mcMatchId();
  const float &chpfcands_1316_phi();
  const vector<float> &genTau_eta();
  const float &nupfcands_2430_pt();
  const vector<int> &genPart_motherId();
  const int &nBJetTight35();
  const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL();
  const float &evt_xsec();
  const vector<int> &lep_convVeto();
  const vector<float> &lep_validfraction();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_up_p4();
  const float &chpfcands_1316_sumet();
  const int &run();
  const float &chpfcands_1624_pt();
  const vector<int> &genLepFromTau_pdgId();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_up_p4();
  const vector<float> &gamma_hcpfclusiso();
  const bool &HLT_Photon75_R9Id90_HE10_IsoM_matchedtophoton();
  const float &met_T1CHS_miniAOD_CORE_pt();
  const int &HLT_Photon50_R9Id90_HE10_IsoM();
  const float &dphi_jj_up();
  const vector<float> &gamma_chHadIso();
  const int &nTrueInt();
  const float &dphi_ll();
  const vector<float> &lep_relIsoUncorr();
  const int &Flag_trackingFailureFilter();
  const int &Flag_goodVertices();
  const float &decayedphoton_mt2();
  const float &chpfcands_1624_sumet();
  const int &HLT_Photon200();
  const int &HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ();
  const int &HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &hyp_type();
  const vector<int> &genLep_sourceId();
  const int &nElectrons10();
  const float &mt2();
  const float &dphi_ll_up();
  const int &HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW();
  const int &HLT_Photon90_R9Id90_HE10_IsoM();
  const float &ht();
  const float &met_T1CHS_fromCORE_phi();
  const int &nBJetTight35_dn();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &highPtPFcands_p4();
  const float &nupfcands_30in_pt();
  const int &isData();
  const vector<float> &genLep_charge();
  const float &weight_btagsf_light_DN();
  const vector<float> &gamma_hollowtkiso03();
  const int &ngenPart();
  const float &dilpt();
  const vector<float> &genLepFromTau_mass();
  const vector<float> &weightsf_lepip();
  const float &mbb_csv_up();
  const bool &HLT_Photon36_R9Id90_HE10_IsoM_matchedtophoton();
  const float &met_genPt();
  const vector<float> &lep_sta_pterrOpt();
  const vector<int> &genLep_pdgId();
  const vector<float> &weightsf_lepid();
  const vector<float> &gamma_drMinParton();
  const float &phpfcands_0013_pt();
  const vector<int> &genPart_grandmaId();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL();
  const float &deta_jj_up();
  const vector<float> &genTau_charge();
  const vector<float> &jets_muf();
  const int &HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL();
  const float &isr_weight();
  const vector<int> &jets_mcHadronFlav();
  const vector<int> &genTau_pdgId();
  const int &HLT_Photon22_R9Id90_HE10_IsoM();
  const int &nVert();
  const vector<float> &gamma_hOverE();
  const vector<float> &genPart_eta();
  const float &evt_filter();
  const int &Flag_duplicateMuons();
  const bool &HLT_Photon90_R9Id90_HE10_IsoM_matchedtophoton();
  const float &sumet_raw();
  const int &Flag_CSCTightHalo2015Filter();
  static void progress( int nEventsTotal, int nEventsChain );
};

#ifndef __CINT__
extern ZMET2016 phys;
#endif

namespace zmet2016 {

  const int &HLT_Mu37_Ele27_CaloIdL_MW();
  const vector<float> &ak8jets_tau1();
  const vector<float> &ak8jets_tau3();
  const vector<float> &ak8jets_tau2();
  const int &HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZ();
  const int &HLT_Mu27_TkMu8();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genPart_p4();
  const int &HLT_Mu50();
  const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL();
  const int &HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &nisoTrack_5gev();
  const float &nupfcands_2430_phi();
  const int &Flag_badMuonFilterv2();
  const vector<float> &isotrack_absiso();
  const float &phpfcands_2430_phi();
  const int &HLT_IsoMu27();
  const vector<float> &genPart_pt();
  const float &isr_unc();
  const float &sum_mlb();
  const float &met_miniaod_pt();
  const vector<int> &lep_charge();
  const int &nlep();
  const float &met_genPhi();
  const float &phpfcands_0013_sumet();
  const vector<int> &lep_lostHits();
  const unsigned long long &evt();
  const vector<int> &gamma_idCutBased();
  const vector<int> &genLepFromTau_status();
  const float &dphi_genmetj1();
  const int &njets();
  const int &mass_LSP();
  const vector<float> &weightsf_lepip_FS();
  const vector<float> &genTau_phi();
  const vector<int> &ak8jets_parton_flavor();
  const int &HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL();
  const float &nupfcands_1316_sumet();
  const vector<float> &jets_csv();
  const float &dphi_metj2_dn();
  const int &Flag_eeBadScFilter();
  const vector<float> &jets_up_csv();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &decayedphoton_bosn_p4();
  const float &dR_jj_dn();
  const vector<int> &genLep_motherIndex();
  const vector<float> &gamma_phIso();
  const vector<float> &lep_etaSC();
  const vector<float> &lep_MVA();
  const int &nBJetTight25();
  const int &nBJetMedium35_dn();
  const int &nTaus20();
  const float &met_T1CHS_miniAOD_CORE_dn_phi();
  const float &phpfcands_30in_sumet();
  const vector<float> &lep_phi();
  const float &met_T1CHS_fromCORE_pt();
  const float &sum_mlb_dn();
  const vector<float> &genPart_mass();
  const bool &HLT_Photon120_R9Id90_HE10_IsoM_matchedtophoton();
  const vector<float> &genLepFromTau_charge();
  const int &evt_nEvts();
  const bool &HLT_Photon165_HE10_matchedtophoton();
  const float &met_calo_pt();
  const float &gen_ht();
  const int &HLT_Mu30_TkMu11();
  const float &deta_jj_dn();
  const int &nBJetLoose25();
  const bool &HLT_Photon50_R9Id90_HE10_IsoM_matchedtophoton();
  const vector<float> &gamma_mass();
  const float &evt_scale1fb();
  const float &met_calo_phi();
  const int &HLT_Mu27_Ele37_CaloIdL_MW();
  const float &phpfcands_2430_pt();
  const float &mjj_mindphi();
  const vector<float> &genTau_mass();
  const int &nJet200MuFrac50DphiMet();
  const vector<float> &genLepFromTau_phi();
  const float &chpfcands_2430_sumet();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &decayedphoton_lep1_p4();
  const vector<float> &genLep_pt();
  const vector<float> &gamma_hOverE_online();
  const int &HLT_singleMu_noiso();
  const float &mbb_bpt_dn();
  const bool &HLT_Photon165_R9Id90_HE10_IsoM_matchedtophoton();
  const float &met_T1CHS_miniAOD_CORE_phi();
  const float &nupfcands_2430_sumet();
  const int &HLT_singleMu();
  const float &mt2_genmet();
  const float &phpfcands_30in_phi();
  const float &nupfcands_1624_sumet();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_dn_p4();
  const float &phpfcands_1316_phi();
  const int &nisoTrack_mt2();
  const float &chpfcands_30in_pt();
  const int &nisoTrack_PFEle5_woverlaps();
  const float &nupfcands_30in_phi();
  const vector<int> &lep_tightCharge();
  const int &nBJetLoose35();
  const int &Flag_HBHEIsoNoiseFilter();
  const int &HLT_Photon30_R9Id90_HE10_IsoM();
  const vector<float> &lep_glb_x2ondof();
  const vector<int> &genLepFromTau_sourceId();
  const float &met_rawPt();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &decayedphoton_lep2_p4();
  const float &met_muegclean_pt();
  const int &HLT_Mu30_Ele30_CaloIdL_GsfTrkIdVL();
  const float &met_T1CHS_pt();
  const float &dphi_metj1_up();
  const int &lumi();
  const bool &elveto();
  const int &HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ();
  const float &chpfcands_30in_phi();
  const float &mjj();
  const float &chpfcands_0013_pt();
  const vector<int> &lep_pdgId();
  const bool &HLT_Photon30_R9Id90_HE10_IsoM_matchedtophoton();
  const vector<float> &lep_relIso03();
  const vector<float> &lep_relIso04();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gamma_p4();
  const int &Flag_EcalDeadCellTriggerPrimitiveFilter();
  const bool &HLT_Photon22_R9Id90_HE10_IsoM_matchedtophoton();
  const int &nBJetMedium25();
  const int &nBJetLoose25_dn();
  const vector<float> &lep_pt();
  const float &weight_L1prefire_down();
  const int &nBJetTight25_dn();
  const vector<float> &gamma_pt();
  const vector<float> &highPtPFcands_dz();
  const vector<float> &weightsf_lepid_FS();
  const vector<int> &genTau_sourceId();
  const float &chpfcands_0013_phi();
  const int &Flag_hcalLaserEventFilter();
  const int &HLT_Photon165_R9Id90_HE10_IsoM();
  const float &chpfcands_2430_pt();
  const float &dphi_jj();
  const int &nBJetLoose35_up();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_p4();
  const vector<int> &gamma_mcMatchId();
  const float &nupfcands_1316_phi();
  const float &met_muegclean_phi();
  const vector<bool> &genPart_isp6status3();
  const vector<float> &lep_x2ondof();
  const float &ht_dn();
  const int &ngenLep();
  const int &year();
  const int &HLT_DoubleEle27_CaloIdL_MW_Edge();
  const vector<float> &genLepFromTau_eta();
  const int &HLT_ECALHT800_NoJetID();
  const vector<float> &gamma_genPt();
  const float &mt2_up();
  const float &mjj_up();
  const vector<unsigned long> &isotrack_index();
  const float &nupfcands_0013_sumet();
  const float &dphi_metj2_up();
  const float &dphi_metj3_up();
  const vector<int> &isotrack_pdgId();
  const float &evt_kfactor();
  const int &nBJetMedium35_up();
  const int &HLT_CaloJet500_NoJetID();
  const vector<float> &lep_relIso03MRDB();
  const int &ngenLepFromTau();
  const float &dphi_genmetj3();
  const float &dphi_metj3_dn();
  const int &HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass8();
  const int &HLT_singleEl();
  const int &HLT_Photon75_R9Id90_HE10_IsoM();
  const float &dRll();
  const int &njets_dn();
  const int &isr_njets();
  const vector<float> &gamma_ecpfclusiso();
  const float &weight_L1prefire_up();
  const float &phpfcands_30in_pt();
  const int &HLT_Photon165_HE10();
  const float &nupfcands_0013_pt();
  const vector<float> &genLep_eta();
  const int &nJetFailId();
  const int &Flag_HBHENoiseFilter();
  const float &deta_jj();
  const float &metsig_unofficial_dn();
  const float &dR_jj();
  const int &nFatJets();
  const int &HLT_Mu37_TkMu27();
  const float &nupfcands_30in_sumet();
  const float &mjj_mindphi_up();
  const int &nBJetLoose35_dn();
  const float &mbb_bpt_up();
  const vector<float> &genTau_pt();
  const int &Flag_noBadMuons();
  const vector<float> &lep_dz();
  const vector<float> &gamma_eta();
  const vector<float> &genPart_phi();
  const vector<float> &weightsf_lepiso();
  const int &Flag_CSCTightHaloFilter();
  const int &nBJetLoose25_up();
  const int &HLT_Mu33_Ele33_CaloIdL_GsfTrkIdVL();
  const vector<int> &lep_tightId();
  const int &nBJetMedium25_up();
  const float &met_T1CHS_miniAOD_CORE_up_phi();
  const float &phpfcands_1624_sumet();
  const int &HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL();
  const float &met_phi();
  const vector<int> &genTau_status();
  const vector<float> &genLep_mass();
  const float &met_T1CHS_phi();
  const float &rho();
  const float &dphi_metj1_dn();
  const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ();
  const int &mass_gluino();
  const int &HLT_DoubleEle33_CaloIdL_MW();
  const vector<TString> &evt_dataset();
  const vector<float> &lep_pterr();
  const float &weight_btagsf_heavy_DN();
  const int &Flag_badChargedCandidateFilter();
  const int &Flag_badChargedCandidateFilterv2();
  const vector<float> &lep_sta_x2ondof();
  const float &dphi_genmetj2();
  const int &nMuons10();
  const int &evt_type();
  const int &HLT_Photon36_R9Id90_HE10_IsoM();
  const float &mjj_dn();
  const vector<float> &weightsf_lepconv();
  const vector<float> &gamma_phi();
  const float &phpfcands_0013_phi();
  const float &nupfcands_1624_pt();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8();
  const vector<float> &gamma_sigmaIetaIeta();
  const int &Flag_globalTightHalo2016();
  const int &mass_chi();
  const vector<bool> &isotrack_isLostTrack();
  const int &nBJetMedium35();
  const int &nisoTrack_PFLep5_woverlaps();
  const int &nBJetTight25_up();
  const vector<float> &gamma_neuHadIso();
  const int &Flag_badMuonFilter();
  const float &matched_emf();
  const vector<float> &lep_dxy();
  const float &chpfcands_1316_pt();
  const vector<int> &genPart_pdgId();
  const vector<int> &jets_mcFlavour();
  const int &nveto_leptons();
  const float &sum_mlb_up();
  const float &nupfcands_1316_pt();
  const int &ngamma();
  const vector<float> &lep_relIso03MREA();
  const float &mjj_mindphi_dn();
  const float &dphi_jj_dn();
  const float &mt2_dn();
  const float &metsig_unofficial_up();
  const float &rho25();
  const int &nisoTrack_PFMu5_woverlaps();
  const float &chpfcands_1624_phi();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &ak8jets_p4();
  const int &HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ();
  const float &mt2b_up();
  const vector<int> &genLep_motherId();
  const float &ht_up();
  const vector<float> &weightsf_lepreco();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_p4();
  const float &phpfcands_1316_sumet();
  const float &met_rawPhi();
  const vector<float> &lep_glb_pterrOpt();
  const vector<bool> &genPart_isPromptFinalState();
  const float &dphi_metj2();
  const float &dphi_metj3();
  const float &dphi_metj1();
  const vector<float> &genLep_phi();
  const float &phpfcands_1316_pt();
  const float &dilmass();
  const float &isrboost();
  const int &nBJetTight35_up();
  const int &ngenTau();
  const float &dphi_ll_dn();
  const int &njets_up();
  const vector<float> &lep_relIso03MRNC();
  const float &chpfcands_2430_phi();
  const vector<int> &highPtPFcands_pdgId();
  const int &nhighPtPFcands();
  const float &met_T1CHS_miniAOD_CORE_up_pt();
  const float &chpfcands_30in_sumet();
  const int &nBadMuons20();
  const int &HLT_DoubleEle25_CaloIdL_MW();
  const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ();
  const float &nupfcands_1624_phi();
  const vector<float> &gamma_r9();
  const float &chpfcands_0013_sumet();
  const int &Flag_ecalLaserCorrFilter();
  const float &weight_btagsf_heavy_UP();
  const vector<float> &gamma_genIso();
  const int &Flag_badMuons();
  const float &metsig_unofficial();
  const int &HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ();
  const vector<float> &ak8jets_softDropMass();
  const vector<float> &lep_eta();
  const vector<int> &genPart_status();
  const vector<float> &weightsf_lepconv_FS();
  const int &nBJetMedium25_dn();
  const float &puWeight();
  const float &met_pt();
  const float &weight_btagsf_light_UP();
  const int &HLT_DoubleEle33_CaloIdL_GsfTrkIdVL();
  const float &nupfcands_0013_phi();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &lep_p4();
  const vector<bool> &genLep_isp6status3();
  const vector<float> &weightsf_lepiso_FS();
  const float &mbb_bpt();
  const vector<int> &genLep_status();
  const vector<int> &gamma_genIsPromptFinalState();
  const float &mbb_csv();
  const float &weight_L1prefire();
  const float &mbb_csv_dn();
  const vector<float> &genLepFromTau_pt();
  const int &nGammas20();
  const bool &evt_passgoodrunlist();
  const float &mt2b();
  const float &mt2j();
  const float &met_T1CHS_miniAOD_CORE_dn_pt();
  const int &HLT_TkMu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &isotrack_p4();
  const int &HLT_Photon120_R9Id90_HE10_IsoM();
  const int &Flag_globalSuperTightHalo2016();
  const float &weight_btagsf();
  const int &HLT_Photon110EB_TightID_TightIso();
  const vector<float> &genPart_charge();
  const float &met_miniaod_phi();
  const vector<float> &jets_dn_csv();
  const float &mt2b_genmet();
  const vector<float> &lep_mass();
  const int &nisoTrack_PFHad10_woverlaps();
  const float &mt_lep1();
  const float &phpfcands_1624_phi();
  const float &phpfcands_1624_pt();
  const float &matched_neutralemf();
  const float &mt2b_dn();
  const float &phpfcands_2430_sumet();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_dn_p4();
  const float &dR_jj_up();
  const vector<int> &lep_mcMatchId();
  const float &chpfcands_1316_phi();
  const vector<float> &genTau_eta();
  const float &nupfcands_2430_pt();
  const vector<int> &genPart_motherId();
  const int &nBJetTight35();
  const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL();
  const float &evt_xsec();
  const vector<int> &lep_convVeto();
  const vector<float> &lep_validfraction();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_up_p4();
  const float &chpfcands_1316_sumet();
  const int &run();
  const float &chpfcands_1624_pt();
  const vector<int> &genLepFromTau_pdgId();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_up_p4();
  const vector<float> &gamma_hcpfclusiso();
  const bool &HLT_Photon75_R9Id90_HE10_IsoM_matchedtophoton();
  const float &met_T1CHS_miniAOD_CORE_pt();
  const int &HLT_Photon50_R9Id90_HE10_IsoM();
  const float &dphi_jj_up();
  const vector<float> &gamma_chHadIso();
  const int &nTrueInt();
  const float &dphi_ll();
  const vector<float> &lep_relIsoUncorr();
  const int &Flag_trackingFailureFilter();
  const int &Flag_goodVertices();
  const float &decayedphoton_mt2();
  const float &chpfcands_1624_sumet();
  const int &HLT_Photon200();
  const int &HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ();
  const int &HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &hyp_type();
  const vector<int> &genLep_sourceId();
  const int &nElectrons10();
  const float &mt2();
  const float &dphi_ll_up();
  const int &HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW();
  const int &HLT_Photon90_R9Id90_HE10_IsoM();
  const float &ht();
  const float &met_T1CHS_fromCORE_phi();
  const int &nBJetTight35_dn();
  const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &highPtPFcands_p4();
  const float &nupfcands_30in_pt();
  const int &isData();
  const vector<float> &genLep_charge();
  const float &weight_btagsf_light_DN();
  const vector<float> &gamma_hollowtkiso03();
  const int &ngenPart();
  const float &dilpt();
  const vector<float> &genLepFromTau_mass();
  const vector<float> &weightsf_lepip();
  const float &mbb_csv_up();
  const bool &HLT_Photon36_R9Id90_HE10_IsoM_matchedtophoton();
  const float &met_genPt();
  const vector<float> &lep_sta_pterrOpt();
  const vector<int> &genLep_pdgId();
  const vector<float> &weightsf_lepid();
  const vector<float> &gamma_drMinParton();
  const float &phpfcands_0013_pt();
  const vector<int> &genPart_grandmaId();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL();
  const float &deta_jj_up();
  const vector<float> &genTau_charge();
  const vector<float> &jets_muf();
  const int &HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL();
  const float &isr_weight();
  const vector<int> &jets_mcHadronFlav();
  const vector<int> &genTau_pdgId();
  const int &HLT_Photon22_R9Id90_HE10_IsoM();
  const int &nVert();
  const vector<float> &gamma_hOverE();
  const vector<float> &genPart_eta();
  const float &evt_filter();
  const int &Flag_duplicateMuons();
  const bool &HLT_Photon90_R9Id90_HE10_IsoM_matchedtophoton();
  const float &sumet_raw();
  const int &Flag_CSCTightHalo2015Filter();
}
#endif
